---
title: "Word Frequency Analysis Notebook"
output: 
  html_notebook:
    theme: cerulean
    toc: yes
    toc_float: yes
---


# Load packages {.tabset}

## Tidyverse
Tidyverse contains many functions useful to cleaning, tidying, and manipulating data

Documentation can be viewed [here](https://www.tidyverse.org)

```{r}
if (!require(tidyverse)){
  install.packages("tidyverse", dependencies = TRUE)
  library(tidyverse)
}
```



# Import data {.tabset}

## get list of private school documents

```{r}
(docs.private <- list.files("Private/"))
```
## get list of public school documents

```{r}
(docs.public <- list.files("Public/"))
```

## import private school alerts
```{r}
school.separator <- "XXXXXnewschoolXXXXX"

for (doc in docs.private)
{
  if(!exists("alerts.private"))
  {
    enframe(read_lines(paste("Private/", doc, sep=""))) %>%
      add_row(value = school.separator) -> alerts.private
  }
  else
  {
    enframe(read_lines(paste("Private/", doc, sep=""))) %>%
      add_row(value = school.separator) %>%
      bind_rows(alerts.private) -> alerts.private
  }
}
alerts.private
```
## import public school alerts
```{r}
for (doc in docs.public)
{
  if(!exists("alerts.public"))
  {
    enframe(read_lines(paste("Public/", doc, sep=""))) %>%
      add_row(value = school.separator) -> alerts.public
  }
  else
  {
    enframe(read_lines(paste("Public/", doc, sep=""))) %>%
      add_row(value = school.separator) %>%
      bind_rows(alerts.public) -> alerts.public
  }
}
alerts.public
```











